'use strict';

var W=(e,t,o=!1)=>{var d,L;return (L=(d=e.toString(t).split(".")[Number(o)])==null?void 0:d.length)!=null?L:0},u=(e,t=10)=>{e=`${e||"0"}.`;let[o,d]=e.split("."),L=parseInt(o||"0",t),I=parseInt(d||"0",t)/Math.pow(t,d.length);return L+I},E=(e,t,o=void 0)=>Math.pow(t,o?o-W(e,t,!0):W(e,t))-e,b=(e,t,o=void 0)=>E(e,t,o)-Math.pow(t,-W(e,t,!0));var p=document.getElementById("content"),k=p==null?void 0:p.children[0].children,F=p==null?void 0:p.children[1].children,w=p==null?void 0:p.children[2].children;F[0].children[1];F[1].children[1];var H=F[2].children[1],T=F[3].children[1],O=w[0],U=w[1],$=w[2],h=w[3],S=0,n=2,s=4,R=e=>{k[S].classList.toggle("active"),S=e,k[e].classList.toggle("active"),O.innerHTML=["Sign and Magnitude","Base-1 Complement","Base Complement"][e],S!==0&&(H.value=H.value.replace("-",""),T.value=T.value.replace("-","")),M();},x=e=>{n=Number(e.value),U.innerHTML=`Base ${n}`,H.value="",T.value="",M();},z=e=>{s=Number(e.value),$.innerHTML=`${s} Digit`,M();},K=e=>{let t=e.selectionStart;e.value=e.value.toUpperCase(),e.setSelectionRange(t,t),M();},P=e=>{let t=e.target;if(e.key.length===1){if(/[A-Za-z0-9]/.test(e.key)){let o=e.key.toUpperCase().charCodeAt(0);if(o<48+n&&o>=48||n>10&&o>=65&&o<65+n-10)return !0}else if(e.key==="."){if(t.value.includes(".")){let o=(t.selectionStart||0)+Number(t.value.indexOf(".")>=(t.selectionStart||0))-1;t.value=t.value.replace(".",""),t.setSelectionRange(o,o);}return !0}else if(e.key==="+"&&t.value.startsWith("-")){let o=(t.selectionStart||1)-1;t.value=t.value.slice(1),t.setSelectionRange(o,o),M();}else if(S===0&&e.key==="-"&&!t.value.startsWith("-")){let o=(t.selectionStart||0)+1;t.value=`-${t.value}`,t.setSelectionRange(o,o),M();}return !1}return !0},M=()=>{let e=()=>{console.log(`----------------------------- Data -----------------------------
`,"M B D       :",S,n,s,`
`,"Original    :",B,g,C,f,`
`,"Parsed      :",r.toFormatString(),c.toFormatString(),`
`,"ComplementM1:",b(r,n,s).toFormatString(),b(c,n,s).toFormatString(),`
`,"Complement  :",E(r,n,s).toFormatString().slice(-s),E(c,n,s).toFormatString().slice(-s),`
----------------------------------------------------------------`);},t=()=>{console.log("case 1"),D=B?"-":"",i=r+c,i.toString(n).length>s&&(y=!0);},o=()=>{console.log("case 2");let l=0;B?l=r+b(c,n,s):l=b(r,n,s)+c;let m=l.toString(n);if(m.length>s){let a=u(m.slice(1),n),v=u(m[0]);console.log("EAC:",a.toFormatString(),v,(a+v).toFormatString()),D="-",i=a+v;}else i=b(l,n,s);},d=()=>{console.log("case 3"),i=r+c,i.toFormatString()[0]==="1"&&(y=!0);},L=()=>{console.log("case 4");let m=(r+c).toString(n),a=u(m.slice(1),n),v=u(m[0]);console.log("EAC:",a.toFormatString(),v,(a+v).toFormatString()),i=a+v,i.toFormatString()[0]==="0"&&(y=!0);},I=()=>{console.log("case 5"),i=r+c;let l=i.toString(n);if(l.length>s){let m=u(l.slice(1),n),a=u(l[0]);console.log("EAC:",m.toFormatString(),a,(m+a).toFormatString()),i=m+a;}},N=()=>{console.log("case 6"),i=u((r+c).toString(n).slice(1),n),i.toFormatString()[0]==="0"&&(y=!0);},A=()=>{console.log("case 7"),i=r+c;let l=i.toString(n);l.length>s&&(i=u(l.slice(1),n));},B=H.value.startsWith("-"),C=T.value.startsWith("-"),g=(B?H.value.slice(1):H.value).padStart(s,"0"),f=(C?T.value.slice(1):T.value).padStart(s,"0");if(g.length-Number(g.includes("."))>s||f.length-Number(g.includes("."))>s){h.style.color="red",h.innerHTML="Invalid input digit";return}let r=u(g,n),c=u(f,n);e();let y=!1,D="",i=0;if(S===0)B===C?t():o();else {let l=(n-1).toString(36).toUpperCase();if(!["0",l].includes(g[0])||!["0",l].includes(f[0])){h.style.color="red",h.innerHTML="Invalid input MSB";return}S===1?g.startsWith("0")&&f.startsWith("0")?d():g.startsWith(l)&&f.startsWith(l)?L():I():S===2&&(g.startsWith("0")&&f.startsWith("0")?d():g.startsWith(l)&&f.startsWith(l)?N():A());}y?(h.style.color="red",h.innerHTML="Overflow"):(h.style.color="lime",h.innerHTML=`${D}${i.toFormatString()}`||"&nbsp;");};Number.prototype.toFormatString=function(){let e=this.toString(n);return e.padStart(s+Number(e.includes(".")),"0").toUpperCase()};window.changeMode=R;window.changeBase=x;window.changeDigit=z;window.toUpper=K;window.checkInput=P;window.calculate=M;M();
